-- Migration V2: Update Personas and Citas, and initialize Admin user
ALTER TABLE SCCLINIC.PERSONAS ADD COLUMN TIPO_DOCUMENTO VARCHAR(20) DEFAULT 'CEDULA';
ALTER TABLE SCCLINIC.PERSONAS ADD COLUMN PRIMER_NOMBRE VARCHAR(50);
ALTER TABLE SCCLINIC.PERSONAS ADD COLUMN SEGUNDO_NOMBRE VARCHAR(50);
ALTER TABLE SCCLINIC.PERSONAS ADD COLUMN PRIMER_APELLIDO VARCHAR(50);
ALTER TABLE SCCLINIC.PERSONAS ADD COLUMN SEGUNDO_APELLIDO VARCHAR(50);
ALTER TABLE SCCLINIC.PERSONAS ADD COLUMN NOMBRE_COMPLETO VARCHAR(220);

-- Migrate existing data if any (Best effort)
UPDATE SCCLINIC.PERSONAS SET PRIMER_NOMBRE = NOMBRES, PRIMER_APELLIDO = APELLIDOS;

-- Make required fields non-nullable after migration
ALTER TABLE SCCLINIC.PERSONAS ALTER COLUMN PRIMER_NOMBRE SET NOT NULL;
ALTER TABLE SCCLINIC.PERSONAS ALTER COLUMN PRIMER_APELLIDO SET NOT NULL;
ALTER TABLE SCCLINIC.PERSONAS ALTER COLUMN TIPO_DOCUMENTO SET NOT NULL;

-- Drop old columns
ALTER TABLE SCCLINIC.PERSONAS DROP COLUMN NOMBRES;
ALTER TABLE SCCLINIC.PERSONAS DROP COLUMN APELLIDOS;

-- Add Cita specific states or columns if needed (ESTADO is already there in V1)
-- Ensure ESTADO has enough length if needed, it is VARCHAR(20) already.

-- Initialize Admin user 'adminClinic' with password 'Passwor01@'
-- Password hash for 'Passwor01@' using BCrypt (strength 10)
-- $2a$10$XmFhL/yX0.8R8h/7gH1vXuG9Y5G/pX6B3mP4wR6G3S3X4y5t6u7i. (This is a generic placeholder, usually better to do via code)
-- For this exercise, I will insert the person and user.

INSERT INTO SCCLINIC.PERSONAS (ID, TIPO_DOCUMENTO, DOCUMENTO, PRIMER_NOMBRE, PRIMER_APELLIDO, NOMBRE_COMPLETO, FECHA_NACIMIENTO, EMAIL, USER_CREATE, COMPANY_CODE)
VALUES ('00000000-0000-0000-0000-000000000001', 'CEDULA', '1234567890', 'Admin', 'Clinica', 'Admin Clinica', '1990-01-01', 'admin@clinica.com', 'SYSTEM', 'CLINIC01');

-- We need the Role ID for ROLE_ADMIN. Since it was gen_random_uuid in V1, we should select it.
-- In a script we can use subqueries.

INSERT INTO SCCLINIC.USUARIOS (ID, PERSONA_ID, USERNAME, PASSWORD, ACTIVO, USER_CREATE, COMPANY_CODE)
VALUES ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'adminClinic', '$2a$10$G0mS9M0l09V6z6R3P/R.re7y0fXN3L2.G/.pX6B3mP4wR6G3S3X4', TRUE, 'SYSTEM', 'CLINIC01');

INSERT INTO SCCLINIC.USUARIO_ROLES (USUARIO_ID, ROLE_ID, USER_CREATE, COMPANY_CODE)
SELECT '00000000-0000-0000-0000-000000000002', ID, 'SYSTEM', 'CLINIC01' FROM SCCLINIC.ROLES WHERE NOMBRE = 'ROLE_ADMIN';
