-- Migration V3: Support for Multi-Clinic Model
-- Author: Antigravity

-- 1. Create CLINICA table in SCCLINIC schema
CREATE TABLE SCCLINIC.CLINICA (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    RUC VARCHAR(13) UNIQUE NOT NULL,
    RAZON_SOCIAL VARCHAR(200),
    NOMBRE_COMERCIAL VARCHAR(200),
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    ES_EMPRESA BOOLEAN NOT NULL DEFAULT FALSE,
    TELEFONO_CELULAR VARCHAR(20),
    TELEFONO_CONVENCIONAL VARCHAR(20),
    EMAIL VARCHAR(100) NOT NULL,
    REPRESENTANTE_ID UUID,
    CODIGO_ACCESO_PORTAL VARCHAR(10) UNIQUE NOT NULL,
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_CLINICA_REPRESENTANTE FOREIGN KEY (REPRESENTANTE_ID) REFERENCES SCCLINIC.PERSONAS(ID)
);

COMMENT ON TABLE SCCLINIC.CLINICA IS 'Almacena la información de las clínicas registradas en el sistema';

-- 2. Add ACTIVO column to ROLES
ALTER TABLE SCCLINIC.ROLES ADD COLUMN ACTIVO BOOLEAN DEFAULT TRUE;

-- 3. Update USUARIOS to link to CLINICA
ALTER TABLE SCCLINIC.USUARIOS ADD COLUMN CLINICA_ID UUID;
ALTER TABLE SCCLINIC.USUARIOS ADD CONSTRAINT FK_USUARIO_CLINICA FOREIGN KEY (CLINICA_ID) REFERENCES SCCLINIC.CLINICA(ID);
CREATE INDEX IDX_USUARIOS_CLINICA ON SCCLINIC.USUARIOS(CLINICA_ID);

-- 4. Update PACIENTES to link to CLINICA
ALTER TABLE SCCLINIC.PACIENTES ADD COLUMN CLINICA_ID UUID;
ALTER TABLE SCCLINIC.PACIENTES ADD CONSTRAINT FK_PACIENTE_CLINICA FOREIGN KEY (CLINICA_ID) REFERENCES SCCLINIC.CLINICA(ID);
CREATE INDEX IDX_PACIENTES_CLINICA ON SCCLINIC.PACIENTES(CLINICA_ID);

-- 5. Update CITAS to link to CLINICA
ALTER TABLE SCCLINIC.CITAS ADD COLUMN CLINICA_ID UUID;
ALTER TABLE SCCLINIC.CITAS ADD CONSTRAINT FK_CITA_CLINICA FOREIGN KEY (CLINICA_ID) REFERENCES SCCLINIC.CLINICA(ID);
CREATE INDEX IDX_CITAS_CLINICA ON SCCLINIC.CITAS(CLINICA_ID);

-- 6. Add indices for RUC and Access Code
CREATE INDEX IDX_CLINICA_RUC ON SCCLINIC.CLINICA(RUC);
CREATE INDEX IDX_CLINICA_CODIGO ON SCCLINIC.CLINICA(CODIGO_ACCESO_PORTAL);
