-- Unified Database Schema for Clinica Management System
-- Version: Final (Unified V1 + V2)
CREATE SCHEMA IF NOT EXISTS SCCLINIC;

-- 1. PERSONAS
CREATE TABLE SCCLINIC.PERSONAS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TIPO_DOCUMENTO VARCHAR(20) NOT NULL DEFAULT 'CEDULA',
    DOCUMENTO VARCHAR(20) NOT NULL UNIQUE,
    PRIMER_NOMBRE VARCHAR(50) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(50),
    NOMBRE_COMPLETO VARCHAR(220),
    FECHA_NACIMIENTO DATE NOT NULL,
    SEXO VARCHAR(20),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL
);

COMMENT ON TABLE SCCLINIC.PERSONAS IS 'Almacena la información básica de todas las personas en el sistema';
COMMENT ON COLUMN SCCLINIC.PERSONAS.ID IS 'Identificador único de la persona';
COMMENT ON COLUMN SCCLINIC.PERSONAS.TIPO_DOCUMENTO IS 'Tipo de documento (CEDULA, PASAPORTE, etc)';
COMMENT ON COLUMN SCCLINIC.PERSONAS.DOCUMENTO IS 'Documento de identidad único';
COMMENT ON COLUMN SCCLINIC.PERSONAS.PRIMER_NOMBRE IS 'Primer nombre de la persona';
COMMENT ON COLUMN SCCLINIC.PERSONAS.SEGUNDO_NOMBRE IS 'Segundo nombre de la persona';
COMMENT ON COLUMN SCCLINIC.PERSONAS.PRIMER_APELLIDO IS 'Primer apellido de la persona';
COMMENT ON COLUMN SCCLINIC.PERSONAS.SEGUNDO_APELLIDO IS 'Segundo apellido de la persona';
COMMENT ON COLUMN SCCLINIC.PERSONAS.NOMBRE_COMPLETO IS 'Nombre completo de la persona';
COMMENT ON COLUMN SCCLINIC.PERSONAS.FECHA_NACIMIENTO IS 'Fecha de nacimiento';
COMMENT ON COLUMN SCCLINIC.PERSONAS.SEXO IS 'Sexo o género';
COMMENT ON COLUMN SCCLINIC.PERSONAS.DIRECCION IS 'Dirección de residencia';
COMMENT ON COLUMN SCCLINIC.PERSONAS.TELEFONO IS 'Número de teléfono';
COMMENT ON COLUMN SCCLINIC.PERSONAS.EMAIL IS 'Correo electrónico';
COMMENT ON COLUMN SCCLINIC.PERSONAS.USER_CREATE IS 'Usuario que creó el registro';
COMMENT ON COLUMN SCCLINIC.PERSONAS.DATE_CREATE IS 'Fecha y hora de creación';
COMMENT ON COLUMN SCCLINIC.PERSONAS.USER_MODIFICATION IS 'Usuario que realizó la última modificación';
COMMENT ON COLUMN SCCLINIC.PERSONAS.DATE_MODIFICATION IS 'Fecha y hora de la última modificación';
COMMENT ON COLUMN SCCLINIC.PERSONAS.COMPANY_CODE IS 'Código de la compañía/empresa para multi-tenencia';

-- 2. ROLES
CREATE TABLE SCCLINIC.ROLES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL
);

COMMENT ON TABLE SCCLINIC.ROLES IS 'Define los roles de acceso para los usuarios';
COMMENT ON COLUMN SCCLINIC.ROLES.ID IS 'Identificador único del rol';
COMMENT ON COLUMN SCCLINIC.ROLES.NOMBRE IS 'Nombre del rol (ej: ROLE_ADMIN)';

-- 3. USUARIOS
CREATE TABLE SCCLINIC.USUARIOS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PERSONA_ID UUID UNIQUE,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ACTIVO BOOLEAN NOT NULL DEFAULT TRUE,
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (PERSONA_ID) REFERENCES SCCLINIC.PERSONAS(ID)
);

-- 4. USUARIO_ROLES (Join Table)
CREATE TABLE SCCLINIC.USUARIO_ROLES (
    USUARIO_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    PRIMARY KEY (USUARIO_ID, ROLE_ID),
    CONSTRAINT FK_UR_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES SCCLINIC.USUARIOS(ID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SCCLINIC.ROLES(ID)
);

-- 5. PACIENTES
CREATE TABLE SCCLINIC.PACIENTES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PERSONA_ID UUID NOT NULL UNIQUE,
    TIPO_SANGRE VARCHAR(5),
    SEGURO_MEDICO VARCHAR(100),
    CONTACTO_EMERGENCIA VARCHAR(255),
    OBSERVACIONES TEXT,
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_PACIENTE_PERSONA FOREIGN KEY (PERSONA_ID) REFERENCES SCCLINIC.PERSONAS(ID)
);

-- 6. HISTORIAS_CLINICAS
CREATE TABLE SCCLINIC.HISTORIAS_CLINICAS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PACIENTE_ID UUID NOT NULL,
    DIAGNOSTICO VARCHAR(1500) NOT NULL,
    TRATAMIENTO VARCHAR(1500) NOT NULL,
    RECETA VARCHAR(1500),
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_HC_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES SCCLINIC.PACIENTES(ID)
);

-- 7. CITAS
CREATE TABLE SCCLINIC.CITAS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PACIENTE_ID UUID NOT NULL,
    PROFESIONAL_ID UUID NOT NULL,
    FECHA_HORA TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    MOTIVO VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES SCCLINIC.PACIENTES(ID),
    CONSTRAINT FK_CITA_PROFESIONAL FOREIGN KEY (PROFESIONAL_ID) REFERENCES SCCLINIC.USUARIOS(ID)
);

-- 8. CONSULTAS
CREATE TABLE SCCLINIC.CONSULTAS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    HISTORIA_ID UUID NOT NULL,
    CITA_ID UUID UNIQUE,
    DIAGNOSTICO TEXT,
    TRATAMIENTO TEXT,
    RECETA TEXT,
    FECHA TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- Audit fields
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_MODIFICATION VARCHAR(100),
    DATE_MODIFICATION TIMESTAMP WITHOUT TIME ZONE,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_CONSULTA_HISTORIA FOREIGN KEY (HISTORIA_ID) REFERENCES SCCLINIC.HISTORIAS_CLINICAS(ID),
    CONSTRAINT FK_CONSULTA_CITA FOREIGN KEY (CITA_ID) REFERENCES SCCLINIC.CITAS(ID)
);

-- 9. REFRESH_TOKENS
CREATE TABLE SCCLINIC.REFRESH_TOKENS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USUARIO_ID UUID NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    EXPIRY_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    USER_CREATE VARCHAR(100) NOT NULL,
    DATE_CREATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPANY_CODE VARCHAR(20) NOT NULL,
    CONSTRAINT FK_RT_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES SCCLINIC.USUARIOS(ID)
);

-- Initial Data
-- Insert Roles
INSERT INTO SCCLINIC.ROLES (ID, NOMBRE, USER_CREATE, COMPANY_CODE) VALUES ('00000000-0000-0000-0000-100000000001', 'ROLE_ADMIN', 'SYSTEM', 'CLINIC01');
INSERT INTO SCCLINIC.ROLES (ID, NOMBRE, USER_CREATE, COMPANY_CODE) VALUES ('00000000-0000-0000-0000-100000000002', 'ROLE_USER', 'SYSTEM', 'CLINIC01');
INSERT INTO SCCLINIC.ROLES (ID, NOMBRE, USER_CREATE, COMPANY_CODE) VALUES ('00000000-0000-0000-0000-100000000003', 'ROLE_MEDICO', 'SYSTEM', 'CLINIC01');

-- Insert Initial Admin Person
INSERT INTO SCCLINIC.PERSONAS (ID, TIPO_DOCUMENTO, DOCUMENTO, PRIMER_NOMBRE, PRIMER_APELLIDO, NOMBRE_COMPLETO, FECHA_NACIMIENTO, EMAIL, USER_CREATE, COMPANY_CODE)
VALUES ('00000000-0000-0000-0000-000000000001', 'CEDULA', '1234567890', 'Admin', 'Clinica', 'Admin Clinica', '1990-01-01', 'admin@clinica.com', 'SYSTEM', 'CLINIC01');

-- Insert Initial Admin User (password is AES encrypted for 'Password01@')
INSERT INTO SCCLINIC.USUARIOS (ID, PERSONA_ID, USERNAME, PASSWORD, ACTIVO, USER_CREATE, COMPANY_CODE)
VALUES ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'adminClinic', 'QT6PdL/IY9l8IL+OQ577JWTAm6aM8z9tdIKxcBdQuq8=', TRUE, 'SYSTEM', 'CLINIC01');

-- Assign Admin Role
INSERT INTO SCCLINIC.USUARIO_ROLES (USUARIO_ID, ROLE_ID, USER_CREATE, COMPANY_CODE)
VALUES ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-100000000001', 'SYSTEM', 'CLINIC01');
